### PR TITLE
Restructuring the Folder Structure

### PR DESCRIPTION
**Pull request by sourabbanka22**
_Based on my past experience with React.js, I have re-structured the folders and files for better efficiency and workflow. Also each components and pages has its own separate CSS file now!_

**@JoseDeFreitas , I hope you like it!**

### CODE REVIEW

**Comment by Tekipeps** [comment]
> _Based on my past experience with React.js, I have re-structured the folders and files for better efficiency and workflow. Also each components and pages has its own separate CSS file now!_
> 
> **@JoseDeFreitas , I hope you like it!**
> 

Thanks for this.. makes styling easier

**Comment by JoseDeFreitas** [comment]
Oh WOW! This is awesome 😮. This makes everything easier to edit and maintain.
Should I wait to merge this PR? Some other people are working on other things... 🤔.
I like this PR a lot and will be merged. I'll just wait for your recommendation on this. Thank you a lot @sourabbanka22.

**Comment by sourabbanka22** [comment]
@JoseDeFreitas, I don't think merging this PR would create any issues for them because ultimately this PR itself will speed up their workflow (since it makes things easier), the only thing that they need to do is: 

1. Pull the new changes to the main branch (Well don't forget to commit the changes of the working branch that you are working on).
2. Create a new branch.
3. And copy the progress from the old branch to the newly created branch.

Well anyways, I'm glad you liked it!

**Comment by sourabbanka22** [comment]
Also, @Tekipeps You're Welcome!

**Comment by Tekipeps** [comment]
> Oh WOW! This is awesome 😮. This makes everything easier to edit and maintain.
> Should I wait to merge this PR? Some other people are working on other things... 🤔.
> I like this PR a lot and will be merged. I'll just wait for your recommendation on this. Thank you a lot @sourabbanka22.

It shouldn't cause any issues.. they can fetch the upstream branch and merge to their work locally it'll be fine

**Comment by JoseDeFreitas** [comment]
Okay! Thank you two for the comments. I'll merge 👌.

**Pull request merged**
