### PR TITLE
Customize the Code

### PR DESCRIPTION
**Pull request by khush31**

### CODE REVIEW

**Comment by JoseDeFreitas** [comment]
Hello! Thank you for adding those comments. They're very helpful. Thank you for submitting this Pull request 😄.

**Comment by khush31** [comment]
> Hello! Thank you for adding those comments. They're very helpful. Thank you for submitting this Pull request 😄.

Good to know you liked this would please label my PR as hacktoberfest-accepted.

**Comment by JoseDeFreitas** [comment]
@khush31 this repository has the "hacktoberfest" topic, so a PR that's merged should work the same as adding the "hacktoberfest-accepted" label. Check your [Hacktoberfest profile](https://hacktoberfest.digitalocean.com/profile) and you should have a PR in "review", which means:
> Your PR has been accepted by a maintainer and is currently within the review period, which lasts for fourteen days.

**Comment by khush31** [comment]
> @khush31 this repository has the "hacktoberfest" topic, so a PR that's merged should work the same as adding the "hacktoberfest-accepted" label. Check your [Hacktoberfest profile](https://hacktoberfest.digitalocean.com/profile) and you should have a PR in "review", which means:
> 
> > Your PR has been accepted by a maintainer and is currently within the review period, which lasts for fourteen days.

Thank you so much @JoseDeFreitas connected with you 

> @khush31 this repository has the "hacktoberfest" topic, so a PR that's merged should work the same as adding the "hacktoberfest-accepted" label. Check your [Hacktoberfest profile](https://hacktoberfest.digitalocean.com/profile) and you should have a PR in "review", which means:
> 
> > Your PR has been accepted by a maintainer and is currently within the review period, which lasts for fourteen days.

ohh Yeah! Sorry I forgot that. It's been great working with you @JoseDeFreitas

**Comment by khush31** [comment]
> @khush31 this repository has the "hacktoberfest" topic, so a PR that's merged should work the same as adding the "hacktoberfest-accepted" label. Check your [Hacktoberfest profile](https://hacktoberfest.digitalocean.com/profile) and you should have a PR in "review", which means:
> 
> > Your PR has been accepted by a maintainer and is currently within the review period, which lasts for fourteen days.

oh Yeah! i forgot that It's been nice working with you @JoseDeFreitas

**Comment by JoseDeFreitas** [comment]
@khush31 no problem. I write the same. Thank you for contributing to my repository 😄.

**Pull request merged**
