### PR TITLE
Migrating from CSS to SCSS

### PR DESCRIPTION
**Pull request by sourabbanka22**
_I think that working on SCSS is more easier than working on CSS since it contains additional features that aren't present in CSS._

**Thus, I migrated the existing project from _CSS to SCSS_.**

### CODE REVIEW

**Comment by Tekipeps** [comment]
When merged contributors make sure to run `npm install`

**Comment by sourabbanka22** [comment]
@JoseDeFreitas, Let me know if there are any changes required!

**Comment by sourabbanka22** [comment]
@JoseDeFreitas, the changes that you just made are causing conflicts, since you have changed the classNames to Ids, its causing conflicts in the styling, that I have committed in this PR, I think we should revert back the ids to the respective classNames, and merge my PR, and then maybe do the remaining changes.

Well that's just my thought, I'm happy to hear your thoughts on this.

**Comment by JoseDeFreitas** [comment]
Hello @sourabbanka22! This is such a big change! Sorry for the late response but I was reviewing the code. It's great.
About the last thing you commented, I've reverted the changes: commit c9d83ee. I'll probably change it again after this Pull request.
Thank you a lot for this huge contribution!

**Pull request merged**
