### PR TITLE
Styling the Navbar

### PR DESCRIPTION
**Pull request by sourabbanka22**
**_Navigation Styling has been improved_**

**Previous Navbar:**
currentNavbar

**New Navbar:**
NewNavbar

### CODE REVIEW

**Comment by JoseDeFreitas** [comment]
Wow 😮, what a nice design! It's friendlier now. I like how the "Result" page is separated from the other sections (it should be like that.) The transitions look good too. Thank you for this nice change 🤟.

**Comment by sourabbanka22** [comment]
@JoseDeFreitas, I'm glad that you liked it!

**Comment by sourabbanka22** [comment]
@JoseDeFreitas, I think that working on SCSS is more easier than working on CSS since it contains additional features that aren't present in CSS.

Let me know your thoughts, If you like **_I can migrate the existing project from CSS to SCSS_**.

**Comment by JoseDeFreitas** [comment]
@sourabbanka22 sure. If you want to add SCSS you can do it. When styling I program mainly in SCSS, but I didn't use it for this project as I didn't know the interaction with React. Let me know how you will install it. I've been working with SCSS using a VSC extension that compiles it into CSS, but I guess it's better installing is as an NPM package. 🎨

**Comment by sourabbanka22** [comment]
You're right, I use an NPM package called **node-sass**. And Thanks! The PR is on the way!

**Pull request merged**
